[package]
edition = "2021"
name = "tlsn-examples"
publish = false
version = "0.0.0"

[dependencies]
actix-web = "4.0"
notary-client.workspace = true
tlsn-core.workspace = true
tlsn-prover = { workspace = true }
tlsn-verifier.workspace = true

futures.workspace = true
http-body-util = "0.1"
hyper = {version = "1.1", features = ["client", "http1"]}
hyper-util = {version = "0.1", features = ["full"]}
rustls = {version = "0.21"}
rustls-pemfile = {version = "1.0.2"}
tokio = {workspace = true, features = [
  "rt",
  "rt-multi-thread",
  "macros",
  "net",
  "io-std",
  "fs",
] }
tokio-util.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

chrono = "0.4"
dotenv = "0.15.0"
elliptic-curve = { version = "0.13.5", features = ["pkcs8"] }
regex = "1.10.3"

[[example]]
name = "simple_prover"
path = "simple/simple_prover.rs"

[[example]]
name = "simple_verifier"
path = "simple/simple_verifier.rs"

[[example]]
name = "twitter_dm"
path = "twitter/twitter_dm.rs"

[[example]]
name = "discord_dm"
path = "discord/discord_dm.rs"

[[example]]
name = "discord_dm_verifier"
path = "discord/discord_dm_verifier.rs"

[[example]]
name = "interactive"
path = "interactive/interactive.rs"

[[example]]
name = "pawa"
path = "pawa/pawa.rs"
