server:
  name: "seree-notary-server"
  host: "0.0.0.0"
  port: 7047
  html-info: |
    <h1>Sereé Notary Server {version}!</h1>
    <ul>
    <li>git commit hash: <a href="https://github.com/seree-fam/tlsn/commit/{git_commit_hash}">{git_commit_hash}</a></li>
    <li>git commit timestamp: {git_commit_timestamp}</li>
    <li>public key: <pre>{public_key}</pre></li>
    </ul>
    <a href="/healthcheck">health check</a> - <a href="/info">info</a><br/>

notarization:
  max-transcript-size: 20480

tls:
  enabled: true
  private-key-pem-path: "./fixture/seree/seree-server.key"
  certificate-pem-path: "./fixture/seree/0001_chain.cert"

notary-key:
  private-key-pem-path: "fixture/seree/seree-notary-private-key.pem"
  public-key-pem-path: "./fixture/seree/seree-notary-public-key.pub"

logging:
  level: DEBUG

authorization:
  enabled: false
  whitelist-csv-path: "./fixture/auth/whitelist.csv"